### ISSUE TITLE
How to use the package?

### ISSUE THREAD

**Issue by RUbyGu** [Interbotix/interbotix_ros_crawlers#2]
Hello, 

We are trying to use the ROS package to simulate the crawler robot in ROS Rviz and Gazebo.
Our system is Ubuntu 16.04 with ROS Kinetic.

We downloaded the  **interbotix_ros_crawlers**,**interbotix_ros_core** as well as the **interbotix_ros_toolboxes** packages.

But when we tried to compile the workspace using the command of Catkin_make, we got a bunch of errors.
We thought maybe it is because of the lack of dependencies.....

We can not find the compiling guidance on the Github page and the Interbotix website.

Could you please tell us how to compile it? and what are the necessary dependencies of this project?

Many thanks for your help.

**Comment by LSinterbotix** [comment]
Hi @RUbyGu! If you just want to run a simulation on a computer with amd64 architecture, please run the following commands. Note that if you previously tried to install everything in a directory named `~/interbotix_ws`, you must first remove or rename that directory.
```
$ sudo apt install curl
$ curl 'https://raw.githubusercontent.com/Interbotix/interbotix_ros_crawlers/main/interbotix_ros_xshexapods/install/amd64/xshexapod_amd64_install.sh' > xshexapod_amd64_install.sh
$ chmod +x xshexapod_amd64_install.sh
$ ./xshexapod_amd64_install.sh
```
The install script will install all dependencies and correctly configure your workspace.

Currently, there is no way to purely simulate the hexapod in Gazebo. However, RVIZ simulation works well if you set Global Options->Fixed Frame to <robot_name>/odom.

To get it working, run the command below (assuming you're simulating a px mark IV hexapod):
```
$ roslaunch interbotix_xshexapod_control xshexapod_control.launch robot_model:=pxmark4 use_sim:=true use_rviz:=true
```
You can then run the [python demos](https://github.com/Interbotix/interbotix_ros_crawlers/tree/main/interbotix_ros_xshexapods/examples/python_demos).

**Comment by TSYMR14** [comment]
Hi @LSinterbotix, I've also had similar errors when trying to build the workspace on ROS Noetic. I have the crawlers, core and toolbox packages downloaded but the **interbotix_xshexapod_gazebo** and **interbotix_xshexapod_control** packages fail to build with a CMake error:
```
CMake Error at /opt/ros/noetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by
  "effort_controllers" with any of the following names:

    effort_controllersConfig.cmake
    effort_controllers-config.cmake

  Add the installation prefix of "effort_controllers" to CMAKE_PREFIX_PATH or
  set "effort_controllers_DIR" to a directory containing one of the above
  files.  If "effort_controllers" provides a separate development package or
  SDK, be sure it has been installed.
```
and a similar error for the files **interbotix_xs_sdkConfig.cmake** and **interbotix_xs_sdk-config.cmake.**

Are these files included in any of the repositories? I can't find them anywhere so I'm not sure what to path to set.
Thanks.

**Comment by LSinterbotix** [comment]
Hi @TSYMR14! Which platform are you trying to run the packages on? Were you able to download and run the correct install script successfully? The script should have installed all of the required dependencies, as well as deleted all CATKIN_IGNORE files that block certain unnecessary packages from building.

**Comment by TSYMR14** [comment]
@LSinterbotix all fixed, I noticed there was some path problems between the interbotix_ws created by the install script and my existing catkin_ws so I deleted all ROS files and work spaces and let the install script add everything back in. It's a bit extreme but I wasn't really using my old catkin_ws and this got everything set up with the correct paths.

**Comment by LSinterbotix** [comment]
@RUbyGu & @TSYMR14, do you have any further questions about the package's usage?

**Comment by LSinterbotix** [comment]
Closing - feel free to reopen if you require any additional help.

**Comment by stuliujiayu** [comment]
I have a similar problem.
ROS version: Melodic
Ubuntu version:18.04
When i install the X-Series Arm packages following the scripe below:
```
 sudo apt install curl
 curl 'https://raw.githubusercontent.com/Interbotix/interbotix_ros_manipulators/main/interbotix_ros_xsarms/install/amd64/xsarm_amd64_install.sh' > xsarm_amd64_install.sh
 chmod +x xsarm_amd64_install.sh
 ./xsarm_amd64_install.sh melodic
```
A problem occurred:
```
Creating config file /etc/ssh/sshd_config with new version
Creating SSH2 RSA key; this may take some time ...
2048 SHA256:y+Edo13n2uc6iu15cYNmqST8VAhVWMSfW8/zoA6Hmsc root@leona (RSA)
Creating SSH2 ECDSA key; this may take some time ...
256 SHA256:mKkvuV+BXq1iQchGgynp60NGPCQCIyoAEGFHaCny/nw root@leona (ECDSA)
Creating SSH2 ED25519 key; this may take some time ...
256 SHA256:nsdTkm5Az4hnEF5KHkw6tn8Iiz/lUzrTwb6e8Lm6SHk root@leona (ED25519)
Created symlink /etc/systemd/system/sshd.service → /lib/systemd/system/ssh.service.
Created symlink /etc/systemd/system/multi-user.target.wants/ssh.service → /lib/systemd/system/ssh.service.
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Processing triggers for ufw (0.36-0ubuntu0.18.04.2) ...
Processing triggers for ureadahead (0.100.0-21) ...
ureadahead will be reprofiled on next reboot
Processing triggers for systemd (237-3ubuntu10.56) ...
./xsarm_amd64_install.sh: line 159: [: ==: unary operator expected
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-pip is already the newest version (9.0.1-2.3~ubuntu1.18.04.5).
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://mirrors.ustc.edu.cn/pypi/web/simple
Collecting modern_robotics
  Downloading https://mirrors.bfsu.edu.cn/pypi/web/packages/a0/78/18a10bb636b0f1ae101efdb8dfe65f5dce231e00de95ae1a14af32c49249/modern_robotics-1.1.0.tar.gz (14 kB)
Requirement already satisfied: numpy in /usr/lib/python2.7/dist-packages (from modern_robotics) (1.13.3)
Building wheels for collected packages: modern-robotics
  Building wheel for modern-robotics (setup.py) ... done
  Created wheel for modern-robotics: filename=modern_robotics-1.1.0-py2-none-any.whl size=16550 sha256=c3643b0781a507d2701b4f409a061d79223b738a32a1ff07ccd8dfb7d1900fa2
  Stored in directory: /home/ljy/.cache/pip/wheels/6e/58/d5/016df3eece29c0560d3cb0c886499ea5e990a68987babdd239
Successfully built modern-robotics
Installing collected packages: modern-robotics
Successfully installed modern-robotics-1.1.0
[ERROR] Something went wrong.
[ERROR] Interbotix Installation Failed!
```
Is the python version lead to the problem? 
What's more, I can't find the file named interbotix_ws.
Could anyone tell me why? Thanks!!!!
