### ISSUE TITLE
[Question]: What would be needed to add hexapod mark 3 support ?

### ISSUE THREAD

**Issue by The-Real-Thisas** [Interbotix/interbotix_ros_crawlers#7]
### Question

What would be needed to add hexapod mark 3 support ?

I know I can just place the required urdf and stl files but the mark 3 uses [DYNAMIXEL AX-12A](https://www.trossenrobotics.com/dynamixel-ax-12-robot-actuator.aspx) servos. 

I would like to know what changes would be needed to add support for the mark 3. 

### Robot Model

mark3

### Operating System

Ubuntu 20.04

### ROS Version

ROS1 Noetic

**Comment by The-Real-Thisas** [comment]
@LSinterbotix @swiz23 @mtrossen small follow up, I was wondering what changes would be needed to get it working on a mark 3 with AX-12A servos

**Comment by lukeschmitt-tr** [comment]
The base ROS interface to the motors is through the [interbotix_xs_sdk](https://github.com/Interbotix/interbotix_ros_core/tree/noetic/interbotix_ros_xseries/interbotix_xs_sdk). The core wraps the [dynamixel_workbench_toolbox](https://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_workbench/). According to ROBOTIS, the toolbox is compatible with the AX-12 servos.

The SDK is designed for the X-Series DYNAMXIELs, so much of its functionality is built up with the assumption that we'd be using those more advanced interfaces. You would have to strip away a lot of that functionality like managing operating modes and change how things like joint limits are managed. The AX-12A motors seem to only operate in a position-based mode with timing controlled by the [Moving Speed register](https://emanual.robotis.com/docs/en/dxl/ax/ax-12a/#moving-speed). On top of that, you will need to modify the Python-ROS API to reflect the changes made to the SDK.

There are probably other things you would need to change to get full compatibility, but this should be a good starting point if you're interested in undertaking this effort. I'll be closing this issue as it's unrelated to the officially supported ROS-based crawlers, but feel free to continue to ask questions in this thread.
